const actionTypes = {
    ADD_TO_CART: 'ADD_TO_CART',
    SET_GRAND_TOTAL: 'SET_GRAND_TOTAL',
    SET_CART_COUNT: 'SET_CART_COUNT',
    REMOVE_ITEM: 'REMOVE_ITEM',
    ORDERCREATED:'ORDERCREATED'

}

export default actionTypes;