const actionTypes = {
    ADD_NEW_USER : 'ADD_NEW_USER',   
    SET_LOGGED_IN: 'SET_LOGGED_IN',
    LOGGED_OUT: 'LOGGED_OUT',
    SET_SHIPPING_INFO: 'SET_SHIPPING_INFO',
    SET_SHIPPING_METHOD: 'SET_SHIPPING_METHOD',  
    SET_LOGGED_IN_USER: 'SET_LOGGED_IN_USER',
    ADD_TO_WISHLIST : 'ADD_TO_WISHLIST',
    REMOVE_FROM_WISHLIST : 'REMOVE_FROM_WISHLIST',
    GET_WISHLIST : 'GET_WISHLIST',
    ADD_TO_ADDRESS : 'ADD_TO_ADDRESS',
    REMOVE_FROM_ADDRESS : 'REMOVE_FROM_ADDRESS',
    
}
export default actionTypes