const appActionTypes = {
  SIGIN_VISIBLE: "SIGIN_VISIBLE",
  SET_FORM_ERROR: "SET_FORM_ERROR",
  ENABLE_LOADER: "ENABLE_LOADER",
  DISABLE_LOADER: "DISABLE_LOADER",
  SET_LOGGIN_ERROR: "SET_LOGGIN_ERROR",
  RESET_FORM_ERROR: "RESET_FORM_ERROR",
  SET_ENABLE_LOGIN_SCREEN: "SET_ENABLE_LOGIN_SCREEN",
  SET_ENABLE_FORGOT_PWD_SCREEN: "SET_ENABLE_FORGOT_PWD_SCREEN",
  SET_CART_VISIBLE: "SET_CART_VISIBLE",
  SET_MOVING_TO_CART: "SET_MOVING_TO_CART",
  GO_TO_PRODUCT_DETAIL: "GO_TO_PRODUCT_DETAIL",
};

export default appActionTypes;
